FROM nginx:alpine

USER root
RUN passwd -d 'root'

# Install SSHD dependencies
RUN apk update \
    && apk --no-cache add openssh \
    && rm -rf /var/cache/apk/* \
    && sed -i s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config \
    && ssh-keygen -A

COPY .ssh /root/.ssh
RUN chmod -R 700 /root/.ssh

COPY nginx_proxy_refresh.sh /opt/nginx_proxy_refresh.sh
COPY cmd.sh /opt/cmd.sh

# Add config
COPY nginx/default.conf /etc/nginx/conf.d/

EXPOSE 22 80 443

CMD /opt/cmd.sh

# add deployment
COPY dist/webapp /usr/share/nginx/html
